### ISSUE TITLE
Windows cross compatibility

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/pytest-flake8dir#103]
As discovered by @joaoe [on flake8-comprehensions](https://github.com/adamchainz/flake8-comprehensions/pull/213#issuecomment-576423745).

Flake8's output differs on Windows, because it outputs the paths, which means e.g. `./example.py` on unices becomes `.\example.py`. It would be good if we translated the paths, or otherwise parsed the output, to allow tests to be written cross-platform.

**Comment by joaoe** [comment]
Or just use `os.path.sep` or `replace("\\","/")`.

Since `Flake8Dir` runs in a local folder, all files start with `./` in the path, so perhaps the best option would be to strip them

**Comment by adamchainz** [comment]
I've added such normalization in the new successor library, pytest-flake8-path: https://github.com/adamchainz/pytest-flake8-path/pull/3
