### ISSUE TITLE
 test_extra_args_version fails if flake8 --version output is too long

### ISSUE THREAD

**Issue by bnavigator** [adamchainz/pytest-flake8dir#126]
If the `flake8 --version` output is too long, it's broken into two lines and lets the test fail.

Output from slightly patched `test_pytest_flake8dir.py` to make it evident:

```
============================================ test session starts ============================================
platform linux -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/abuild/rpmbuild/BUILD/pytest-flake8dir-2.2.0
plugins: flake8dir-2.2.0
collected 10 items                                                                                          

tests/test_pytest_flake8dir.py::test_make_py_files_single PASSED                                      [ 10%]
tests/test_pytest_flake8dir.py::test_make_py_files_double PASSED                                      [ 20%]
tests/test_pytest_flake8dir.py::test_make_py_files_no_positional_args PASSED                          [ 30%]
tests/test_pytest_flake8dir.py::test_make_py_files_requires_at_least_one_kwarg PASSED                 [ 40%]
tests/test_pytest_flake8dir.py::test_make_example_py PASSED                                           [ 50%]
tests/test_pytest_flake8dir.py::test_make_setup_cfg PASSED                                            [ 60%]
tests/test_pytest_flake8dir.py::test_make_file PASSED                                                 [ 70%]
tests/test_pytest_flake8dir.py::test_extra_args PASSED                                                [ 80%]
tests/test_pytest_flake8dir.py::test_extra_args_version FAILED                                        [ 90%]
tests/test_pytest_flake8dir.py::test_separate_tmpdir PASSED                                           [100%]

================================================= FAILURES ==================================================
__________________________________________ test_extra_args_version __________________________________________

flake8dir = <pytest_flake8dir.Flake8Dir object at 0x7ffb889febe0>

    def test_extra_args_version(flake8dir):
        result = flake8dir.run_flake8(extra_args=["--version"])
        print(result.out_lines)
>       assert len(result.out_lines) == 1
E       assert 2 == 1
E         +2
E         -1

tests/test_pytest_flake8dir.py:108: AssertionError
------------------------------------------- Captured stdout call --------------------------------------------
['3.8.1 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.2 on', 'Linux']
========================================== short test summary info ==========================================
FAILED tests/test_pytest_flake8dir.py::test_extra_args_version - assert 2 == 1
======================================== 1 failed, 9 passed in 1.81s ========================================
```

**Comment by adamchainz** [comment]
It seems this is caused by the new flake8 release this week.

For all of my packages I only support running the tests under `tox` with the pinned dependencies in the repo's `requirements` folder. I then update the pinned dependencies fortnightly. This avoids the busywork of writing tests that support arbitrary environments.

This particular test failure will be dealt with when I do my next dependency update, to check against the new flake8 version.

For repackaging, I think it's preferable that you use the [github tarballs](https://github.com/adamchainz/pytest-flake8dir/releases) and run the tests via `tox`. I'm planning on dropping tests from my projects' PyPI sdists at some point since 99% of users don't use them, and it's wasted bandwidth/processing/disk space.

Thank you!

**Comment by bnavigator** [comment]
Thanks.

The suggested approach is not entirely applicable to OpenSUSE packaging (tox), but [the package](https://build.opensuse.org/package/view_file/devel:languages:python:pytest/python-pytest-flake8dir/python-pytest-flake8dir.spec?expand=1) already builds from the github tarball. I just removed the `assert len()` line for now.

**Comment by adamchainz** [comment]
That `sed` will break in a week or so when I upgrade and inevitably change the test

Better to do something like disable the test by renaming it `s/test_extra_args_version/disabled_test_extra_args_version/` ?

**Comment by bnavigator** [comment]
The package spec will have to be changed for the next version anyway. If the test is fixed by then, the whole line can be removed. It is very specific to the 2.0.0 release tarball. Master already has the line on a different line number.
