### ISSUE TITLE
Return stderr in addition to stdout

### ISSUE THREAD

**Issue by djmattyg007** [adamchainz/pytest-flake8dir#221]
I've just added a bunch of deprecation warnings to a plugin, but I have no way of testing them using this package because no information about stderr is returned. Ideally, I would be able to add tests to verify that the deprecation warnings are firing correctly.

**Comment by adamchainz** [comment]
Released in 2.6.0!

**Comment by djmattyg007** [comment]
Wow, thank you!

**Comment by adamchainz** [comment]
In fact, I started work after on #173, and you should probably use my new package [pytest-flake8-path](https://github.com/adamchainz/pytest-flake8-path/).
