### ISSUE TITLE
Document preferred method of installing the plugin under test

### ISSUE THREAD

**Issue by jamescooke** [adamchainz/pytest-flake8dir#28]
Adam - this looks great. I've got it wired in on https://github.com/jamescooke/flake8-aaa and looks like it provides a great integration test layer.

In order to get `flake8` to load my plugin when I run `pytest`, I've had to do `pip install -e .` . Is there a better way to do this? I think it would be a good idea to document your tried and tested method if possible.

**Comment by adamchainz** [comment]
I run my tests under `tox`, that does `pip install .` for you (not sure if with `-e`). I think it's best practice to use `tox` or something else that does `pip install` for you, that verifies your `setup.py` works!

**Comment by jamescooke** [comment]
Thanks for the suggestion - I hadn't thought of using `tox`.
