### ISSUE TITLE
`run_flake8` does not return version string

### ISSUE THREAD

**Issue by jamescooke** [adamchainz/pytest-flake8dir#33]
This test fails unexpectedly: https://github.com/jamescooke/pytest-flake8dir/commit/b88470b7c931cd815562d7d873d09e64d3b6c924 (note the extra space required in `' --version'` before the first hyphen. Without this argparse crashes in flake8.

I was expecting the version string to be returned so that I could test that the plugin has been installed with the expected name and version number.

Running with the args via the command line works:

```sh
$ flake8 --jobs 1 --exit-zero . --version
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.5.2 on Linux
```

Loading `main` in `ipython` and calling that directly works (even though it raises):

```
In [1]: from flake8.main.cli import main

In [2]: main(argv=['--jobs', '1', '--exit-zero', '.', '--version'])
3.5.0 (My flake8 plugin: 0.0, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.5.2 on Linux
An exception has occurred, use %tb to see the full traceback.

SystemExit: 0
[ipython warning about exit]
```

I'm wondering if this is something to do with how Flake8 does something special with `--version`: https://github.com/PyCQA/flake8/blob/master/src/flake8/main/application.py#L96

**Comment by adamchainz** [comment]
It's probably that space you're adding, which is equivalent to running `flake8 ' --version'`, which is a weird no-op when I try:

```sh
$ flake8 ' --version'
$ echo $?
0
```

I think it's trying to find a file called `' --version'`, argparse won't parse it as an argument because it doesn't start with `--`. What's the crash you were seeing when doing it without the space? That will be the most informative.

**Comment by jamescooke** [comment]
Ahh - `flake8 ' --version'` is a good call :+1: 

Here's the failing build with `extra_args=['--version']` : https://travis-ci.org/jamescooke/pytest-flake8dir/builds/346026397

**Comment by adamchainz** [comment]
Try version 1.2.0! https://pypi.org/project/pytest-flake8dir

**Comment by jamescooke** [comment]
Works great :+1: Thanks!
